#!/bin/sh

width=250
height=200
datefmt="+%a %d %b" 

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) datefmt="$OPTARG" ;;
        W) width="$OPTARG" ;;
        H) height="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

	posX=500
	posY=500

	i3-msg -q "exec yad --calendar \
      --width=$width --height=$height \
	    --undecorated --fixed \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac
date "$datefmt"
#	    --close-on-unfocus --no-buttons \
