#!/usr/bin/python3

import dbus
import os
import sys

STATUS_TO_ICON = {
    1: '',
    0: '',
}


BUS_NAME = 'org.gmusicbrowser'
OBJECT_PATH = '/org/gmusicbrowser'
PLAYER_INTERFACE = 'org.gmusicbrowser.Player'

try:

    bus = dbus.SessionBus()
    obj = bus.get_object("org.gmusicbrowser","/org/gmusicbrowser")
    gmusicbrowser = bus.get_object(BUS_NAME, OBJECT_PATH)
    gmusicbrowser_iface = dbus.Interface(obj, "org.gmusicbrowser")
#
    if os.environ.get('BLOCK_BUTTON'):
        if (os.environ['BLOCK_BUTTON'] == '1'):
            gmusicbrowser_iface.RunCommand("PrevSong")     
        elif (os.environ['BLOCK_BUTTON'] == '2'):
            gmusicbrowser_iface.RunCommand("PlayPause")     
        elif (os.environ['BLOCK_BUTTON'] == '3'):
            gmusicbrowser_iface.RunCommand("NextSong")     

    info = gmusicbrowser_iface.CurrentSong()

    status = gmusicbrowser_iface.Playing()
    status_icon = STATUS_TO_ICON.get(status, '?')

    print("[ " + status_icon + " ] "  + str(info['artist']) + " - " + str(info['title']) )

    
#except dbus.exceptions.DBusException:
except dbus.DBusException as ex:
    print(ex.message)
    exit
